# Generated by Django 5.2.4 on 2025-09-21 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripation',
            new_name='description',
        ),
    ]
